// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkuYPyMcgTJ4FBl8wJ4-ZctIshxAz505M',
    appId: '1:101436238734:web:3a082e5d671e4d39ff92df',
    messagingSenderId: '101436238734',
    projectId: 'autogolfcrm-messaging',
    authDomain: 'autogolfcrm-messaging.firebaseapp.com',
    storageBucket: 'autogolfcrm-messaging.firebasestorage.app',
    measurementId: 'G-LJEKXS1EP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB88lKjes3zXeszyUjll85-0YJorZ_Atzk',
    appId: '1:101436238734:android:79880c733be09b34ff92df',
    messagingSenderId: '101436238734',
    projectId: 'autogolfcrm-messaging',
    storageBucket: 'autogolfcrm-messaging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEOYkNI_tV7WoLvs2zhUkiL6oNYDgXxnY',
    appId: '1:101436238734:ios:e2e727d584fd95b0ff92df',
    messagingSenderId: '101436238734',
    projectId: 'autogolfcrm-messaging',
    storageBucket: 'autogolfcrm-messaging.firebasestorage.app',
    iosBundleId: 'com.enabletech.autogolfcrm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEOYkNI_tV7WoLvs2zhUkiL6oNYDgXxnY',
    appId: '1:101436238734:ios:e2e727d584fd95b0ff92df',
    messagingSenderId: '101436238734',
    projectId: 'autogolfcrm-messaging',
    storageBucket: 'autogolfcrm-messaging.firebasestorage.app',
    iosBundleId: 'com.enabletech.autogolfcrm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwsGmHtSWW9LdaO8R0I6wftQPkHtnUy94',
    appId: '1:224974438083:web:5dfe79140a6fe10cfcec76',
    messagingSenderId: '224974438083',
    projectId: 'mgpfunctions',
    authDomain: 'mgpfunctions.firebaseapp.com',
    storageBucket: 'mgpfunctions.firebasestorage.app',
    measurementId: 'G-0S32LNP1EL',
  );
}