// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwsGmHtSWW9LdaO8R0I6wftQPkHtnUy94',
    appId: '1:224974438083:web:5dfe79140a6fe10cfcec76',
    messagingSenderId: '224974438083',
    projectId: 'mgpfunctions',
    authDomain: 'mgpfunctions.firebaseapp.com',
    storageBucket: 'mgpfunctions.firebasestorage.app',
    measurementId: 'G-0S32LNP1EL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP9L4ngwK0iiOINxXxyunSoG0xpboK8rs',
    appId: '1:224974438083:android:3e69715c0dd1f054fcec76',
    messagingSenderId: '224974438083',
    projectId: 'mgpfunctions',
    storageBucket: 'mgpfunctions.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkwOPXKAdktsnDnLHRjjvyyh8m8BDQwA4',
    appId: '1:224974438083:ios:3b4c22e92a6d0039fcec76',
    messagingSenderId: '224974438083',
    projectId: 'mgpfunctions',
    storageBucket: 'mgpfunctions.firebasestorage.app',
    iosBundleId: 'mygolfplanner.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkwOPXKAdktsnDnLHRjjvyyh8m8BDQwA4',
    appId: '1:224974438083:ios:3b4c22e92a6d0039fcec76',
    messagingSenderId: '224974438083',
    projectId: 'mgpfunctions',
    storageBucket: 'mgpfunctions.firebasestorage.app',
    iosBundleId: 'mygolfplanner.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwsGmHtSWW9LdaO8R0I6wftQPkHtnUy94',
    appId: '1:224974438083:web:5dfe79140a6fe10cfcec76',
    messagingSenderId: '224974438083',
    projectId: 'mgpfunctions',
    authDomain: 'mgpfunctions.firebaseapp.com',
    storageBucket: 'mgpfunctions.firebasestorage.app',
    measurementId: 'G-0S32LNP1EL',
  );
}